### ISSUE TITLE
Can't use padding Writer instance twice

### ISSUE THREAD

**Issue by kiyonlin** [muesli/reflow#13]
I don't know if it is a bug or an intended/designed choose.
```go
package main

import (
	"fmt"
	"io"

	"github.com/muesli/reflow/padding"
)

func main() {
	width := uint(6)
	b := []byte("foo")

	// padding uses spaces per default:
	f := padding.NewWriter(width, nil)

	// but you can also use a custom padding function:
	f = padding.NewWriter(width, func(w io.Writer) {
		w.Write([]byte("."))
	})

	f.Write(b)
	f.Close()
	
	// foo...
	fmt.Println(f.String())

	f.Write(b)
	f.Close()

	// foo...foo
	fmt.Println(f.String())
}
```

**Comment by kiyonlin** [comment]
If it is a bug, I think we can fix it by resetting buffer when closing.

**Comment by muesli** [comment]
I don't consider it a bug, but common design for writers instead. If you closed the writer, you can't write to it anymore.

**Comment by kiyonlin** [comment]
> I don't consider it a bug, but common design for writers instead. If you closed the writer, you can't write to it anymore.

Okey, this makes sense. But should we handle rewrite action if a writer was closed? Like return an error or panic.

And should we provide `Flush` method so that we can reuse the writer?

**Comment by muesli** [comment]
Good point, further writes should probably return an error. I wouldn't mind a `Flush` method!

**Comment by kiyonlin** [comment]
> Good point, further writes should probably return an error. I wouldn't mind a `Flush` method!

I'll submit PR about these.
