### ISSUE TITLE
New optimized write performance seems to break glamor

### ISSUE THREAD

**Issue by zavislak** [muesli/reflow#23]
The recent change (in ansi.Writer) to iterating over bytes instead of runes seems to break glamor's UTF-8 processing here: https://github.com/charmbracelet/glamour/blob/master/ansi/margin.go

The first indent pipe (using ansi.Writer) breaks up UTF-8 byte sequences into single byte writes, which are misinterpreted when ingested into the second padding pipe, as they go through a byte->string->[]byte conversion.

Here's an illustration of the effect:
https://play.golang.org/p/N-caKzuAwdQ

_Originally posted by @zavislak in https://github.com/muesli/reflow/pull/10#r510675805_

**Comment by kiyonlin** [comment]
Copy from https://github.com/muesli/reflow/pull/10#discussion_r510678786

Hey @zavislak I don't know why you use `bad = append(bad, []byte(string(c))[0])`

You can see this demo instead. https://play.golang.org/p/fHX2TW2-ORG

**Comment by kiyonlin** [comment]
Do you have more detail examples?

**Comment by zavislak** [comment]
This should illustrate the problem better: https://play.golang.org/p/RLOMbGDu3RV

If you convert a single byte of the a UTF-8 sequence to a string, go will mangle it.  This is in effect what happens when the new ansi.Writer outputs the sequences one byte at a time, when downstream code tries to reinterpret these single bytes as strings (as padding.go does).

I found this by building glow at head.  Let me know if glow properly shows UTF-8 sequences for you.

**Comment by kiyonlin** [comment]
> I believe you can build glow at head and see the broken UTF-8 sequences, which led me to try track this down to happening between the indent and padding pipes in glamor. If glow properly handles utf-8 for you at head, please let me know.

We can discuss here. One thing you should notice is all changes are not released yet.

**Comment by zavislak** [comment]
in that case, another way to see this is to modify glamour's helloworld example to include a UTF-8 multi-character sequence.

**Comment by kiyonlin** [comment]
> If you convert a single byte of the a UTF-8 sequence to a string, go will mangle it.

I don't think this gonna happen. `ansi.Writer` is just a wrapper which doesn't care about the original non-ansi bytes.

**Comment by kiyonlin** [comment]
You can view the [test case](https://github.com/muesli/reflow/blob/master/ansi/writer_test.go#L10-L38).

It is best if there is code that can reproduce the bug.

**Comment by zavislak** [comment]
The problem is not ansi.Writer in isolation, but that this change now causes single bytes to be written instead of full UTF-8 runes.  Downstream consumers like padding.go's Write method cast these single byte writes into strings, misinterpreting them.

You can just modify https://github.com/charmbracelet/glamour/blob/master/examples/helloworld/main.go to include a UTF-8 character sequence, which will reproduce the problem.

**Comment by kiyonlin** [comment]
> You can just modify https://github.com/charmbracelet/glamour/blob/master/examples/helloworld/main.go to include a UTF-8 character sequence, which will reproduce the problem.

Sorry, I didn't catch one.

![image](https://user-images.githubusercontent.com/1214670/96971970-7a61f200-1548-11eb-9025-ad84d5f37a43.png)

**Comment by kiyonlin** [comment]
Once upgrade to master version, I saw the broken string. Will do some investigations.

Thanks for reporting!

**Comment by zavislak** [comment]
Cheers!  Was going to just say go get github.com/muesli/reflow@aa57fa9 first.

**Comment by kiyonlin** [comment]
@zavislak Fixed by iterating in string. Wait @muesli to handle the PR.

Or you can get the latest commit from my repo.
