### ISSUE TITLE
BytesWithTail and StringsWithTail should put tail between escape sequences

### ISSUE THREAD

**Issue by heaths** [muesli/reflow#35]
When a trail is added to stylized (e.g. color) text, it would be great if the tail (e.g. ellipsis) was included in the sequence.

For example, consider the string: `\x1b[0;31mexample\x1b[0m`. If part of the string is replaced, it's the string within the vterm sequence that is replaced; thus, the ellipsis should be before the vterm sequence as well: `\x1b[0;31mex...\x1b[0m`

**Comment by muesli** [comment]
Thanks, @heaths! Fixed by #36.
