### ISSUE TITLE
Add dedent package

### ISSUE THREAD

**Issue by lukasmalkmus** [muesli/reflow#5]
Awesome work with this package, really what I was looking for. I could clean up a lot of duplicated helper functions by replacing it with this library.

I have a feature request: Dedentation. It is quite helpful. I currently use a helper function and spotted some code in https://github.com/cli/cli doing the same. It is essentially:

```go
func dedent(s string) string {
	lines := strings.Split(s, "\n")
	minIndent := -1

	for _, l := range lines {
		if len(l) == 0 {
			continue
		}

		indent := len(l) - len(strings.TrimLeft(l, " "))
		if minIndent == -1 || indent < minIndent {
			minIndent = indent
		}
	}

	if minIndent <= 0 {
		return s
	}

	var buf bytes.Buffer
	for _, l := range lines {
		fmt.Fprintln(&buf, strings.TrimPrefix(l, strings.Repeat(" ", minIndent)))
	}
	return strings.TrimSuffix(buf.String(), "\n")
}
```

The algorithm behind that is simple: Find the longest indentation possible for all lines and dedent each line by that.

If you like the idea, I can make a PR and add some tests.

**Comment by muesli** [comment]
Thanks for the kind words! Your suggestion sounds great, please send a PR!
