### ISSUE TITLE
Working with tabs?

### ISSUE THREAD

**Issue by johngebbie** [muesli/reflow#51]
Hello and thank you for making this!
I was just wondering if you have a solution for tabs, which reflow seems to count as one column, but their width is really dependent on the terminal and their position with the tabstop.

For now I've got my pager program replacing tabs with eight spaces but it's not ideal for the navigation and copy pasting.
I'm not sure how programs like Vim (or the libraries) cope with tabs and truncating etc.

Thanks again,
John

**Comment by muesli** [comment]
As you correctly point out, the tab width isn't something reflow could detect. Some of the writers let you set a `TabWidth`, so you can manually specify the tab width you want to work with.
