### ISSUE TITLE
Consider adding extra repository write users

### ISSUE THREAD

**Issue by mikelorant** [muesli/reflow#74]
This package is a core component of the Bubble Tea ecosystem as it is heavily used by Lip Gloss and Bubbles.

There has been no new release since May 2021.

There are also a number of open pull requests that would provide many benefits that have not been reviewed or merged.

While I appreciate the work @muesli has done maintaining this package, I am wondering if it may help to have some more active developers with write access. There is a lot of small changes that could be done that would have benefits for many Bubble Tea components.

I'd also add that it would be very useful to automatically add reviewers to newly created pull requests. Currently, it is hard to know who has write access to request them to review a change.

**Comment by muesli** [comment]
First things first: I'm happy to add you as a collaborator on the project! I'm still reviewing and pondering on your PR, sorry that this will take a few days.

As you correctly pointed out though, any changes on this package have wide-reaching effects for the entire ecosystem around `bubbletea` & `lipgloss`. As such I'm always a bit hesitant to just post a "LGTM" and click the merge button. I'll typically try the changes manually with a couple of the more prominent `bubbletea` applications and benchmark their `View` methods directly. This also applies to other packages in the same stack, as `lipgloss` or `termenv` for example.

So while I understand that the collaborator status makes life on your behalf a lot easier, please do have the patience for my feedback and reviews. I hope this leads to less breakages and a stable API, and the entire ecosystem typically benefits from this.

**Comment by mikelorant** [comment]
Thanks for the explanation, definitely don't want to make it sound like your effort maintaining this repository isn't appreciated. I know you are involved with many repositories being on the charmbracelet team.

Just so you understand, I come from a background of small pull requests that are merged relatively quickly. With the cycle taking longer here, the overall work I want to do on reflow as well as lipgloss and bubbles slows me down. My intention is to significantly improve the emoji support across the entire charmbracelet suite of apps, but this is going to take many PRs. Both reflow and go-runewidth are so heavily used that it has been a difficult process upgrading everything to be consistent.

I was hoping to rapid fire very small changes fixing the issues as I go. I'm not a fan of large pull requests that take a long time to review (the current PR I have up here is far larger than I prefer). But I am aware that it might be easier for one PR to get merged than many with how PRs have generally been reviewed here.

Let me know how I can help though, providing details that make review easier is something that I can do. Adding more tests or benchmarks may also provide more confidence that the changes made will not cause regressions. Asking those that put up pull requests to meet your standard is a reasonable request. This is where a contributing guideline really comes in handy. I was honestly trying to make thing easier for you by providing extensive benchmarking results and requesting assistance from an external developer of a dependency.

**Comment by mikelorant** [comment]
Closing this issue as [charmbracelet/x/exp/term][1] is a modern replacement for this module and has addressed many of the outstanding issues.

[1]: https://github.com/charmbracelet/x/tree/main/exp/term
